/* Auto generated by IronLox.SourceGeneration */

namespace IronLox.SyntaxTree.Statements;

public class ExpressionStatement(IExpression expression) : IStatement
{
    public IExpression Expression { get; } = expression;

    public T Accept<T>(IStatementVisitor<T> visitor) => visitor.Visit(this);
}