/* Auto generated by IronLox.GenerateAst */

namespace IronLox.Ast;

public class Grouping(IExpression expression) : IExpression
{
	public IExpression Expression { get; } = expression;

	public T Accept<T>(IVisitor<T> visitor) => visitor.Visit(this);
}