/* Auto generated by IronLox.GenerateAst */

namespace IronLox.Ast;

public interface IVisitor<T>
{
	T Visit(Binary element);
	T Visit(Grouping element);
	T Visit(Literal element);
	T Visit(Unary element);
}
