/* Auto generated by IronLox.GenerateAst */

namespace IronLox.Ast;

public class Literal(object? value) : IExpression
{
	public object? Value { get; } = value;

	public T Accept<T>(IVisitor<T> visitor) => visitor.Visit(this);
}