/* Auto generated by IronLox.GenerateAst */

using IronLox.Scanning;

namespace IronLox.Ast;

public class Unary(Token @operator, IExpression right) : IExpression
{
    public Token Operator { get; } = @operator;
    public IExpression Right { get; } = right;

    public T Accept<T>(IVisitor<T> visitor) => visitor.Visit(this);
}