/* Auto generated by IronLox.SourceGeneration */

using IronLox.SyntaxTree.Expressions;

namespace IronLox.SyntaxTree;

public interface IExpressionVisitor<T>
{
    T Visit(BinaryExpression element);
    T Visit(GroupingExpression element);
    T Visit(LiteralExpression element);
    T Visit(UnaryExpression element);
}
