/* Auto generated by IronLox.SourceGeneration */

using IronLox.SyntaxTree.Expressions;

namespace IronLox.SyntaxTree;

public interface IExpressionVisitor<T>
{
    T Visit(Binary element);
    T Visit(Grouping element);
    T Visit(Literal element);
    T Visit(Unary element);
}
