/* Auto generated by IronLox.SourceGeneration */

using IronLox.SyntaxTree.Statements;

namespace IronLox.SyntaxTree;

public interface IStatementVisitor<T>
{
    T Visit(ExpressionStatement element);
    T Visit(PrintStatement element);
}
