/* Auto generated by IronLox.SourceGeneration */

using IronLox.Scanning;

namespace IronLox.SyntaxTree.Expressions;

public class Binary(IExpression left, Token @operator, IExpression right) : IExpression
{
    public IExpression Left { get; } = left;
    public Token Operator { get; } = @operator;
    public IExpression Right { get; } = right;

    public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.Visit(this);
}