/* Auto generated by IronLox.SourceGeneration */

namespace IronLox.SyntaxTree.Expressions;

public class Literal(object? value) : IExpression
{
	public object? Value { get; } = value;

	public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.Visit(this);
}