/* Auto generated by IronLox.SourceGeneration */

namespace IronLox.SyntaxTree.Expressions;

public class LiteralExpression(object? value) : IExpression
{
    public object? Value { get; } = value;

    public T Accept<T>(IExpressionVisitor<T> visitor) => visitor.Visit(this);
}